version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: enshx/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    env_file: .env
    image: enshx/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: enshx/kittygram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/mediafiles
    ports:
      - 9000:80
    depends_on:
      - backend